FROM golang:latest

RUN apt-get update && apt-get install -y make bash

WORKDIR /app

COPY ./ /app

RUN go mod download -x

COPY --from=itinance/swag /root/swag /usr/local/bin

RUN go install -mod=mod github.com/swaggo/swag/cmd/swag@latest

RUN go build -o main main.go
RUN swag init
RUN chmod +x fix-swagger-files.sh

ENTRYPOINT -exclude-dir=.git -exclude-dir=docs --command=./main